---
author: Oliver Patterson (S3723206), Kaizhe Huang (S3686152)
date: "21/05/2022"
fontsize: 12pt
header-includes:
    - \usepackage{booktabs}
    - \usepackage{dcolumn}
    - \usepackage{wrapfig}
    - \usepackage{subcaption}
    - \usepackage{caption}
    - \usepackage{graphicx}
    - \usepackage{float}
    - \usepackage{fancyhdr}
    - \usepackage{keyval}
    - \floatplacement{figure}{H}
documentclass: "article"
geometry: margin=2cm
output:
    pdf_document:
        fig_caption: yes
        fig_height: 3
        fig_width: 4.5
        latex_engine: pdflatex
        number_sections: yes
        citation_package: "biblatex"
bibliography: referencing/cites.bib
biblio-style: ieee
nocite: '@*'
---
\pagestyle{empty}

\let\origfigure\figure
\let\endorigfigure\endfigure
\renewenvironment{figure}[1][2] {
    \expandafter\origfigure\expandafter[H]
} {
    \endorigfigure
}
\begin{centering}

\vspace{5 cm}

\Huge

{\bf Advanced Digital Design 1 \\ (EEET2162) \\ Laboratory Project }

\vspace{4 cm}

\Large

Oliver Patterson (S3723206)\\
Kaizhe Huang (S3686152)

\vspace{4 cm}

\normalsize

\vspace{0.5 cm}

Laboratory Demonstrator: \\
Genevieve Fahey

\vspace{0.5 cm}

Date: \\
21/05/2022

\vspace{4 cm}

\normalsize

RMIT School of \\
Engineering

\end{centering}
\newpage
\pagenumbering{roman}
\pagestyle{fancy}
\renewcommand{\headrulewidth}{1pt}
\renewcommand{\footrulewidth}{1pt}
\setlength{\headheight}{15pt}
\fancyhf{}
\fancyhead[L]{Laboratory 1}
\fancyhead[R]{}
\fancyfoot[C]{\thepage}
\clearpage
\pagenumbering{roman}
# Acknowledgements

# Executive Summary

\newpage
\tableofcontents
\newpage
\pagenumbering{arabic}

# Introdution

# Literature Search

# Technical Work and Results

\newpage
# References
\printbibliography[heading=none]
\def\printbibliography{}

# Appendices
